# Top-level configuration
name = "acmcsufcom"
main = "./.cloudflare/worker.js"
compatibility_date = "2025-09-25"
compatibility_flags = { "nodejs_compat" }

[build]
command = "npm run build"

[assets]
directory = "./static/assets"
binding = "ASSETS"

# [env.production]
# name = "acmcsuf-worker-prod"
# route = { pattern = "acmcsuf.com/*", zone_name = "acmcsuf.com" }

# [env.staging]
# name = "my-worker-staging"
# route = { pattern = "staging.example.org/*", zone_name = "example.org" }

# kv_namespaces = [
#   { binding = "<MY_NAMESPACE>", id = "<STAGING_KV_ID>" }
# ]
